from typing import TypedDict, List, Annotated, Optional
import operator
from langchain_core.messages import BaseMessage

from pydantic import BaseModel, Field, ConfigDict

class ErrorSchema(BaseModel):
    model_config = ConfigDict(strict=True)
    type: str = Field(
        default="about:blank",
        description="A URI reference that identifies the problem type.",
    )
    status : int = Field(
        ...,
        description="The HTTP status code generated by the origin server.",
        strict=True
    )
    detail : Optional[str] = Field(
        None,
        description="A human-readable explanation specific to this occurrence.",
    )
    recovery_hint : Optional[str] = Field(
        None, 
        description="A human-readable recovery-hint specific to this occurrence.",
    )

class IncidentState(TypedDict):
    messages : Annotated[List[BaseMessage], operator.add]
    incident_id : str
    telemetry_context : str
    finops_context : str
    remediation_plan : str

